version: '3'
services:
  slimevr-database:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: slimevr
      PGUSER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: slimevr
    volumes:
      - database-volume:/var/lib/postgresql/data
    networks:
      - slimevr-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 1m
      timeout: 5s
      start_period: 2m
      start_interval: 1s
      retries: 5
  slimevr-api:
    build:
      context: .
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      slimevr-database:
        condition: service_healthy
      slimevr-api-s3:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    networks:
      - slimevr-network
    secrets:
      - access_key
      - secret_key
    environment:
      APP_ENV: ${APP_ENV}
      LISTEN_HOST: ${LISTEN_HOST}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_BUILDS_BUCKET: ${S3_BUILDS_BUCKET}
      GITHUB_AUTH: ${GITHUB_AUTH}
      HOST_URL: ${HOST_URL}
  slimevr-api-s3:
    image: minio/minio:latest
    ports:
      - 127.0.0.1:9099:9099
    volumes:
      - storage-minio:/data
    secrets:
      - access_key
      - secret_key
    command: server --address ":9099" --console-address ":9000" /data/disk{1...4}
    restart: unless-stopped
    networks:
      - slimevr-network
    healthcheck:
      test: ["CMD", "mc", "ping", "local", "-c", "1"]
      interval: 1m
      timeout: 5s
      start_period: 2m
      start_interval: 1s
      retries: 5
  slimevr-api-s3-init:
    image: minio/mc:latest
    depends_on:
      slimevr-api-s3:
        condition: service_healthy
    networks:
      - slimevr-network
    secrets:
      - access_key
      - secret_key
    entrypoint: >
      /bin/sh -xc "
      /usr/bin/mc alias set slimevr http://slimevr-api-s3:9099 `cat /run/secrets/access_key` `cat /run/secrets/secret_key`;
      /usr/bin/mc admin update slimevr;
      /usr/bin/mc mb --ignore-existing slimevr/slimevr-firmware-builds;
      /usr/bin/mc anonymous set download slimevr/slimevr-firmware-builds;
      exit 0;
      "

volumes:
  database-volume:
  storage-minio:
    external: false

secrets:
  access_key:
    file: ./docker/minio/access_key.txt
  secret_key:
    file: ./docker/minio/secret_key.txt

networks:
  slimevr-network:
